swagger: '2.0'
info:
  version: 0.0.1
  title: Markdown Storage/Processor App
host: 'localhost:10010'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /markdown:
    x-swagger-router-controller: markdown
    put:
      consumes:
        - text/plain; charset=utf-8
      description: Saves markdown text and converted HTML to Persistent Storage
      operationId: saveMarkdown
      parameters:
        - name: markdown
          in: formData
          required: true
          type: string
      responses:
        '201':
          description: Document created
          schema:
            $ref: '#/definitions/StoreResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/markdown/{id}':
    x-swagger-router-controller: markdown
    get:
      description: Returns markdown and associated HTML
      operationId: getMarkdown
      parameters:
        - name: id
          in: path
          description: ID of the markdown Document
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/MarkdownResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  StoreResponse:
    required:
      - url
    properties:
      url:
        type: string
  MarkdownResponse:
    required:
      - source
      - html
    properties:
      source:
        type: string
      html:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
